# Site settings
title: Pattern Matching with TypeScript | Manuel Alabor
description: TypeScript does not have any pattern matching functionality built in. This article shows several ways how you can replicate the core of a simple pattern matcher using a few simple structures and functions within TypeScript.

# Build settings
markdown: kramdown
sass:
  style: compressed
